# ==================================================================================================
# Spring Settings
# ==================================================================================================
server:
  port: 8000
